# Generated by Django 4.1 on 2022-08-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow_unique_follows'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follows',
        ),
    ]
